(() => {
  const root=document.getElementById('searchBuilder'); if(!root||typeof db==='undefined')return;
  const commands={
    gender:{male:{pt:'macho',en:'male'},female:{pt:'fêmea',en:'female'}},
    size:{xxs:{pt:'xxs',en:'xxs'},xs:{pt:'xs',en:'xs'},xl:{pt:'xl',en:'xl'},xxl:{pt:'xxl',en:'xxl'}},
    iv:{perfect:{pt:'4*',en:'4*'},great:{pt:'3*',en:'3*'},attack:{pt:'4ataque',en:'4attack'}},
    buddy:{buddy:{pt:'companheiro',en:'buddy'}, candy:{pt:'countcandy100-',en:'candycount100-'}},
    status:{shiny:{pt:'brilhante',en:'shiny'},lucky:{pt:'sortudo',en:'lucky'},costume:{pt:'fantasia',en:'costume'}}
  };
  root.innerHTML=`<h2>🧩 Monte sua busca</h2><p class="search-builder-intro">Diga o que você quer encontrar e o GO Nexus monta uma combinação de tags para copiar no Pokémon GO.</p><div class="sb-grid"><div class="sb-field"><label for="sb-species">Pokémon</label><input id="sb-species" placeholder="Ex.: Pikachu" autocomplete="off"></div><div class="sb-field"><label for="sb-candy">Doces mínimos</label><input id="sb-candy" type="number" min="0" step="1" placeholder="Opcional"></div><div class="sb-field"><label for="sb-cp">PC mínimo</label><input id="sb-cp" type="number" min="0" step="1" placeholder="Opcional"></div><div class="sb-field"><label for="sb-lang">Comando em</label><select id="sb-lang"><option value="pt">Português</option><option value="en">English</option></select></div></div><div class="sb-group"><div class="sb-group-title">IV e avaliação</div><div class="sb-chips" data-group="iv"><button class="sb-chip" data-key="perfect">4* · 100%</button><button class="sb-chip" data-key="great">3* · 3 estrelas</button><button class="sb-chip" data-key="attack">Ataque 15</button></div></div><div class="sb-group"><div class="sb-group-title">Companheiro e coleção</div><div class="sb-chips" data-group="buddy"><button class="sb-chip" data-key="buddy">É companheiro</button><button class="sb-chip" data-key="candy">100 doces ou mais</button></div></div><div class="sb-group"><div class="sb-group-title">Gênero e tamanho</div><div class="sb-chips" data-group="gender"><button class="sb-chip" data-key="male">Macho</button><button class="sb-chip" data-key="female">Fêmea</button></div><div class="sb-chips" data-group="size"><button class="sb-chip" data-key="xxs">XXS</button><button class="sb-chip" data-key="xs">XS</button><button class="sb-chip" data-key="xl">XL</button><button class="sb-chip" data-key="xxl">XXL</button></div></div><div class="sb-group"><div class="sb-group-title">Outras tags</div><div class="sb-chips" data-group="status"><button class="sb-chip" data-key="shiny">Brilhante</button><button class="sb-chip" data-key="lucky">Sortudo</button><button class="sb-chip" data-key="costume">Fantasia</button></div></div><div class="sb-actions"><code class="sb-result" id="sb-result">Digite um Pokémon ou escolha um critério</code><button type="button" class="sb-copy" id="sb-copy" disabled>Copiar tag</button></div><div class="sb-feedback" id="sb-feedback">Use &amp; para exigir todos os critérios juntos. Exemplo: Pikachu macho XXL com 100 doces.</div><button type="button" class="sb-clear" id="sb-clear">Limpar montador</button>`;
  const state={selected:new Map()}; const lang=()=>root.querySelector('#sb-lang').value;
  const allItems=()=>[...root.querySelectorAll('.sb-chip.active')].map(b=>({group:b.parentElement.dataset.group,key:b.dataset.key}));
  function findKnown(pt,en){const wanted=lang()==='pt'?pt:en;return db.flatMap(x=>x[1]).find(i=>i.pt===wanted||i.en===wanted);}
  function render(){
    const l=lang(), species=root.querySelector('#sb-species').value.trim(), candies=Number(root.querySelector('#sb-candy').value), cp=Number(root.querySelector('#sb-cp').value); const parts=[];if(species)parts.push(species.toLowerCase().replace(/\s+/g,''));
    allItems().forEach(({group,key})=>{const c=commands[group]?.[key];if(c)parts.push(c[l]);}); if(candies>0)parts.push(l==='pt'?`totaldoce${candies}-`:`candycount${candies}-`);if(cp>0)parts.push(`cp${cp}-`);
    const result=parts.join('&');root.querySelector('#sb-result').textContent=result||'Digite um Pokémon ou escolha um critério';root.querySelector('#sb-copy').disabled=!result;
    const feedback=root.querySelector('#sb-feedback');const unknown=[];allItems().forEach(({group,key})=>{const c=commands[group]?.[key];if(c&&!findKnown(c.pt,c.en))unknown.push(l==='pt'?c.pt:c.en)});feedback.classList.toggle('warn',unknown.length>0);feedback.textContent=unknown.length?`A tag ${unknown.join(', ')} não está no catálogo do guia; confira no jogo antes de usar.`:result?`Busca combinada pronta: todos os critérios serão exigidos ao mesmo tempo. ${parts.length>1?'Essa combinação usa & e pode ser copiada diretamente.':''}`:'Use & para exigir todos os critérios juntos. Exemplo: Pikachu macho XXL com 100 doces.';
  }
  root.querySelectorAll('.sb-chip').forEach(b=>b.onclick=()=>{const group=b.parentElement.dataset.group;if(group==='gender'||group==='iv'&&['perfect','great'].includes(b.dataset.key)){root.querySelectorAll(`[data-group="${group}"] .sb-chip`).forEach(x=>x!==b&&x.classList.remove('active'));}b.classList.toggle('active');render();});root.querySelectorAll('input,select').forEach(e=>e.addEventListener('input',render));root.querySelector('#sb-lang').addEventListener('change',render);root.querySelector('#sb-copy').onclick=async()=>{const value=root.querySelector('#sb-result').textContent;try{await navigator.clipboard.writeText(value);root.querySelector('#sb-copy').textContent='✓ Copiado';setTimeout(()=>root.querySelector('#sb-copy').textContent='Copiar tag',1200)}catch{}};root.querySelector('#sb-clear').onclick=()=>{root.querySelectorAll('.sb-chip.active').forEach(x=>x.classList.remove('active'));root.querySelectorAll('input').forEach(x=>x.value='');render()};render();
})();
